name: Checkout Code

on: [push, pull_request]

jobs:
  checkout:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Checkout pull request
        run: gh pr checkout ${{ github.event.pull_request.number }}
